set -g exit-unattached on
set -g destroy-unattached on
set -g status off
bind-key p command-prompt -p 'save history to filename:' -I '~/tmux.history' 'capture-pane -JS -32768 ; save-buffer %1 ; delete-buffer'
#set -g default-terminal "st-256color"
set -g history-limit 20000
set-option -sg escape-time 0
setw -g mouse on

set -g mode-keys vi
bind-key -n C-f copy-mode \; send-key ?


unbind-key -T copy-mode-vi MouseDragEnd1Pane

